samples_base: "./data/videos"
checkpoint_dir: "./checkpoints"
train_ids: [1, 3, 6, 7, 10, 13, 15, 16, 18, 22, 23, 31, 32, 36, 38, 39, 40, 41, 42, 48, 50, 52, 53, 54]
val_ids: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]
test_ids: [4, 5, 9, 11, 14, 20, 21, 25, 29, 34, 35, 37, 43, 44, 45, 47]
num_epochs: 10
batch_size: 4
learning_rate: 0.0001
patience: 5
num_workers: 4
wandb_project: "volleyball_group_activity"
wandb_run_name: "local_test_3dcnn"
window_before: 3
window_after: 4
image_size: 320

# Model configuration
model_type: "3d_cnn"  # Options: "3d_cnn", "2d_lstm", etc.
resnet_size: "18"     # For 3D CNN: "18" (ResNet3D-18), could extend to "50" if supported


# Additional model parameters:
resnet_size: "50"
person_hidden_dim: 256
group_hidden_dim: 256
person_lstm_layers: 1
group_lstm_layers: 1
bidirectional: false
pretrained: true

# Optionally, choose a transform mode: "none" or "val"
transform: "none"
